name: Build and push to gh-pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - '.github/**'
      - 'README.md'
jobs:
  Build: 
    name: 'Build'
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[skip build]'))"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js LTS
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependendencies
        run: npm install
      - name: Configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Build
        run: npm run deploy